#ifndef BMS_PORT_CONFIG_H
#define BMS_PORT_CONFIG_H

#define BMS_PORT_SAMPLE_PERIOD_MS 100u
#define BMS_PORT_PACK_CAPACITY_AH 18.0f
#define BMS_PORT_INITIAL_SOC_PERCENT 72.0f
#define BMS_PORT_ADC_REFERENCE_V 3.3f
#define BMS_PORT_ADC_MAX_COUNT 4095.0f
#define BMS_PORT_CELL_DIVIDER_SCALE 5.12f
#define BMS_PORT_CURRENT_ZERO_A 0.0f
#define BMS_PORT_CURRENT_SCALE_A_PER_V 40.0f

#endif

